FROM node:current-alpine3.16

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json /app/package.json

RUN npm install
RUN npm install @vue/cli@latest -g

CMD ["npm", "run", "serve"]
