FROM node:17

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY --chown=node:node package.json .

RUN npm upgrade && npm install

COPY --chown=node:node . .
USER node

EXPOSE 8081

CMD ["npm", "start"]
