version: '3.9'

services:

  frontend_udemy:
    restart: always
    container_name: frontend_udemy
    hostname: frontend_udemy
    build:
      context: ./frontend/my-app
      dockerfile: Dockerfile-dev
    volumes:
      - './frontend/my-app:/app/'
      - '/app/node_modules'
    depends_on:
      - postgres_udemy
      - backend_udemy
    ports:
      - 4242:4242
    networks:
      - ft_trance

  backend_udemy:
    restart: always
    container_name: backend_udemy
    hostname: backend_udemy
    build:
      context: ./backend/my-app
      dockerfile: Dockerfile-dev
    volumes:
      - './backend/my-app:/app/'
      - '/app/node_modules'
    depends_on:
      - postgres_udemy
    ports:
      - 3000:3000
    networks:
      - ft_trance

  postgres_udemy:
    restart: always
    user: "root:root"
    container_name: postgres_udemy
    hostname: postgres_udemy
    image: postgres:latest
    volumes:
      - './postgres_vol:/var/lib/postgresql/data'
    ports:
      - 5432:5432
    networks:
      - ft_trance
    environment:
      POSTGRES_PASSWORD:    ${POSTGRES_PASSWORD}
      POSTGRES_USER:        ${POSTGRES_USER}
      POSTGRES_DB:          ${POSTGRES_DB}

networks:
  ft_trance:
    driver: bridge
    name: ft_trance
