services:
  backend:
    restart: always
    hostname: backend
    depends_on:
      - postgres
    networks:
      - ft_trance
    build:
      context: ./backend
      target: dev
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
      - 3001:3001
      - 3002:3002
    volumes:
      - ./backend/src/:/backend/src/:delegated

  frontend:
    depends_on:
      - backend
    restart: always
    hostname: frontend
    networks:
      - ft_trance
    build:
      context: ./frontend
      target: dev
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - ./frontend/src/:/frontend/src/:delegated

  postgres:
    restart: always
    hostname: postgres
    image: postgres:latest
    volumes:
      - ./postgres_vol/:/var/lib/postgresql/data:delegated
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - ft_trance
    environment:
      POSTGRES_PASSWORD:    ${POSTGRES_PASSWORD}
      POSTGRES_USER:        ${POSTGRES_USER}
      POSTGRES_DB:          ${POSTGRES_DB}

networks:
  ft_trance:
    driver: bridge
    name: ft_trance
