FROM node:current-alpine3.16 as development

WORKDIR /usr/src/app

COPY *.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:current-alpine3.16 as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY *.json ./

RUN npm install --only=production

COPY . .

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/main"]
