FROM node:17

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY *.json .

RUN npm install && npm install rxjs  express cors morgan nodemon dotenv axios express-session query-string && npm install -g @nestjs/cli
RUN npm install --save @nestjs/typeorm typeorm mysql

COPY . .

CMD ["npm", "run", "start:dev"]
