FROM node:current-alpine3.16

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY *.json ./

RUN npm update && npm install --only=development && npm install @nestjs/cli@latest -g

CMD ["npm", "run", "start:dev"]
