FROM node:current-alpine3.16

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json /app/package.json

RUN npm install --only=development
RUN npm install @nestjs/cli@latest -g

CMD ["npm", "run", "start:dev"]
